site_name: CeVIO AI 用户指南
site_description: 非官方的 CeVIO AI 用户指南中文版翻译
repo_url: https://github.com/CeVIO-User-Guide-Unofficial/CeVIO-AI
repo_name: CUGU/CeVIO-AI

# Theme
theme:
  custom_dir: 'overrides/material'                  # This is where the customization of the theme lives
  name: material
  features:
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.footer
  icon:
    logo: fontawesome/solid/book
    favicon: images/c-solid.png
    repo: fontawesome/brands/github
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: light blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/CeVIO_st
      name: CeVIO on Twitter

# CSS
extra_css:
  - assets/stylesheets/extra.css

# Extensions
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - tables
  - toc:
      toc_depth: 6

plugins:
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - build: true
          default: true
          locale: zh
          name: 中文（简体）
          nav_translations:
            Audio Track: 音频轨道
            External Interface: 外部调用接口
            FAQ and Bugs: FAQ和已知问题
            First Guide: 入门
            Home: 首页
            Introduction: 简介
            Operation: 基本操作
            Options: 选项
            Others: 其他
            Shortcut Key: 快捷键
            Song Track: 歌唱轨道
            Talk Track: 语音轨道
          site_name: CeVIO AI 用户指南（非官方译文）
        - build: true
          default: false
          locale: en
          name: English
          site_name: CeVIO AI User Guide (Unofficial Translation)
      reconfigure_material: true
      reconfigure_search: true
  - search
  - glightbox
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  # - offline
      # enabled: !ENV [OFFLINE, false]

# Contents
nav:
  - Home: index.md
  - Introduction:
    - intro/change-log.md
    - intro/change-log_website.md
    - intro/contact.md
    - intro/about.md
  - First Guide:
    - firstguide/system_requirements.md
    - firstguide/install.md
    - firstguide/install_cn_patch.md
  - Operation:
    - operation/operation.md
    - operation/menu.md
    - operation/transport.md
    - operation/infopanel.md
    - operation/trackhead.md
    - operation/edittool.md
    - operation/adjusttool.md
  - Talk Track:
    - talktrack/tutorial_talk.md
    - talktrack/talktrack.md
    - talktrack/talk_01.md
    - talktrack/longsentence.md
    - talktrack/talk_02.md
    - talktrack/talk_05.md
    - talktrack/phoneme.md
    - talktrack/phoneme_english.md
    - talktrack/talk_06.md
    - talktrack/talk_01_english.md
    - talktrack/phrasececlip.md
    - talktrack/search.md
    - talktrack/talk_04.md
  - Song Track:
    - songtrack/tutorial_song.md
    - songtrack/songtrack.md
    - songtrack/songtrack_copy.md
    - songtrack/song_02.md
    - songtrack/song_04.md
    - songtrack/song_04_english.md
    - songtrack/song_symbol.md
    - songtrack/song_03.md
    - songtrack/song_05.md
    - songtrack/song_07.md
    - songtrack/song_06.md
    - songtrack/fileimport.md
  - Audio Track:
    - audio/audio.md
  - Options:
    - option/option.md
    - option/characterimage.md
  - Shortcut Key:
    - shortcutkey/shortcutkey.md
  - External Interface:
    - interface/interface.md
    - interface/com.md
    - interface/dotnet.md
  - FAQ and Bugs:
    - faq/faq.md
    - faq/known_bugs.md
  - Others:
    - others/voices_and_official_websites.md
    - others/third_party_websites.md
    - others/emotion_in_song_editor.md
    - others/revised_license_agreement.md
    - others/suzuki_tsudumi_song_contest_result.md
